# Docker Compose configuration for Vibe Chess
# Orchestrates frontend (React + Vite), backend (Node.js), and MongoDB services

version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: vibe-chess-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - vibe-chess-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vibe-chess-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/vibe_chess
      - JWT_SECRET=your-secret-key-change-in-production
    depends_on:
      - mongo
    networks:
      - vibe-chess-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: vibe-chess-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - vibe-chess-network
    restart: unless-stopped

networks:
  vibe-chess-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
