version: '3.8'
# Docker Compose configuration for Vibe Chess
# Note: Dockerfiles need to be created in frontend/ and backend/ directories
# before this configuration can be used.

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: vibe-chess-frontend
    ports:
      - "5173:5173"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - vibe-chess-network
    depends_on:
      - backend
    restart: unless-stopped
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vibe-chess-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
    networks:
      - vibe-chess-network
    restart: unless-stopped

networks:
  vibe-chess-network:
    driver: bridge
      - NODE_ENV=development
